// Copyright (c) 2024 Hemashushu <hippospark@gmail.com>, All rights reserved.
//
// This Source Code Form is subject to the terms of
// the Mozilla Public License version 2.0 and additional exceptions,
// more details in file LICENSE, LICENSE.additional and CONTRIBUTING.

use crate::image::Image;

pub struct Instance<'a, 'b> {
    pub image: &'a Image,
    pub chars: &'b [char], // the source text
    // pub number_of_captures: usize, // for reseting 'capture_positions'
    // pub number_of_counters: usize, // for reseting 'counters' and 'anchors'
    pub threads: Vec<Thread>,
    pub capture_positions: Vec<CapturePosition>, // the results of matches
    pub counters: Vec<usize>,                    // repetitions counters
    pub anchors: Vec<Vec<usize>>,                // the anchors
}

// the anchors
// -----------
// anchors are generated by the greedy repetitions, they
// are used for back tracking.
//
// demo:
//
// 1. normal mode
//
// start                                 end
// |====*================================| <-- cursor 0
//      ^__ position (move to right only)
//
// 2. backtracking
//
// start                                 end
// |-------------------------------------|
// |          v-- pos                    |
// |====#=#=#=*==========================| <-- cursor 0
// |    ^ ^ ^ ^                          |
// |    | | | |===*======================| <-- cursor 1
// | anchors/ ^   ^__ pos' (move to right only)
// |          |__ start' (move to left by anchor only)
// |                                     |
// |-------------------------------------|
//
// 3. return to normal mode
//
// start                                 end
// |=========*===========================| <-- cursor 0
//           ^__ position (move to right only)
//
//
// 4. backtracking within backtracking
//
// start                                 end
// |-------------------------------------|
// |            v-- pos                  |
// |======#==#==*========================| <-- cursor 0
// | anchors ^  ^            v-- pos'    |
// |            |====#===#===*===========| <-- cursor 1
// |    start'__^            ^           |
// |                         |===*=======| <-- cursor 2
// |                start''__^   ^__ pos''
// |                                     |
// |-------------------------------------|
//
// 5. return to normal mode again
//
// start                                 end
// 0                                     len
// |==================*=================| <-- cursor 0
//                    ^__ position (move to right only)

pub struct Thread {
    pub start_position: usize, // poisition included
    pub end_position: usize,   // position excluded
    pub stateset_index: usize, //
    // pub cursor_stack: Vec<Cursor>, // the `Cursor` stack.
    pub stack: Vec<Task>,
}

impl Thread {
    pub fn new(start_position: usize, end_position: usize, stateset_index: usize) -> Thread {
        Thread {
            start_position,
            end_position,
            stateset_index,
            stack: vec![], // cursor_stack: vec![Cursor::new(start, end)],
        }
    }

    // pub fn get_position(&self) -> usize {
    //     self.stack.last().unwrap().position
    // }
}

pub struct Task {
    pub position: usize,
    pub state_index: usize,
    pub transition_index: usize,
}

impl Task {
    pub fn new(position: usize, state_index: usize, transition_index: usize) -> Self {
        Task {
            position,
            state_index,
            transition_index,
        }
    }
}

/*
// The `Cursor` can only be moved to left as a whole,
// and cannot exceed the `position` of the previous `Cursor` (if it exists).
// If the previous `Cursor` does not exist, it cannot be moved.
pub struct Cursor {
    pub start: usize, // position included
    pub end: usize,   // position excluded.

    // store the positions of greedy repetition for
    // backtracking.
    pub anchors: Vec<usize>,

    // the position of the currently matched character.
    // unlike the `start` position of `Cursor`, this value can only
    // be increased (moved to right).
    pub position: usize,
}

impl Cursor {
    pub fn new(start: usize, end: usize) -> Self {
        Cursor {
            start,
            end,
            anchors: vec![],
            position: start,
        }
    }
}
 */

#[derive(Debug, PartialEq, Clone, Copy, Default)]
pub struct CapturePosition {
    pub start: usize,        // position included
    pub end_included: usize, // position included
}

impl<'a, 'b> Instance<'a, 'b> {
    pub fn new(
        image: &'a Image,
        chars: &'b [char],
        // number_of_captures: usize,
        // number_of_counters: usize,
    ) -> Self {
        Instance {
            image,
            chars,
            // number_of_captures,
            // number_of_counters,
            threads: vec![],
            capture_positions: vec![],
            counters: vec![],
            anchors: vec![],
        }
    }

    // pub fn reset(&mut self, start: usize, end: usize) {
    //     self.threads = vec![Thread::new(start, end, MAIN_STATESET_INDEX)];
    //     self.capture_positions = vec![CapturePosition::default(); self.number_of_captures];
    //     self.counters = vec![0; self.number_of_counters];
    //     self.anchors = vec![vec![]; self.number_of_counters];
    // }

    pub fn append_tasks_by_state(&mut self, state_index: usize, position: usize) {
        let transition_count = {
            let thread = self.get_current_thread_ref();
            let stateset_index = thread.stateset_index;
            let state = &self.image.statesets[stateset_index].states[state_index];
            state.transitions.len()
        };

        // add the index of transitions in reverse order,
        // since stack pops the last element first.
        let thread = self.get_current_thread_ref_mut();
        for transition_index in (0..transition_count).rev() {
            thread
                .stack
                .push(Task::new(position, state_index, transition_index));
        }
    }

    #[inline]
    pub fn get_current_thread_ref(&self) -> &Thread {
        self.threads.last().unwrap()
    }

    #[inline]
    pub fn get_current_thread_ref_mut(&mut self) -> &mut Thread {
        let count = self.threads.len();
        &mut self.threads[count - 1]
    }
}
